### ISSUE TITLE
HBP-server: pagination

### ISSUE THREAD

**Issue by claudiughioc** [initiativaromania/HBP-web#3]
Define here how pagination would work.

**Comment by gserb** [comment]
http://hbp-api.azurewebsites.net/api/SearchAD/crema/2

For the moment only SearchAD and SearchTender have pagination.

**Comment by claudiughioc** [comment]
Still needs work, add pagination for all the list API functions

**Comment by claudiughioc** [comment]
TODO pagination for the functions that list items
