### ISSUE TITLE
Add company type in search

### ISSUE THREAD

**Issue by claudiughioc** [initiativaromania/HBP-web#5]
http://hbp-api.azurewebsites.net/api/SearchCompany/pascani
This returns objects such as this one:
{
CompanieId: 1565250,
Nume: "SC TURISM SIRETUL PASCANI SA",
CUI: "1996804",
Tara: "Romania",
Localitate: "Pascani",
Adresa: "PASCANI STR.MOLDOVEI NR.2 JUD.IASI"
},

We need to know if a company is an AD or Tender Company. You can add a new field in the response.

**Comment by gserb** [comment]
Solved by creating SearchADCompany and SearchTenderCompany
