### ISSUE TITLE
HBP-server: add number of ADs and Tenders for Companies

### ISSUE THREAD

**Issue by claudiughioc** [initiativaromania/HBP-web#8]
Please include two result fields for ADCompany and TenderCompany requests which return the number of ADs and Tenders respectively, as it happens for PublicInstitutionSummary.

**Comment by gserb** [comment]
Done. 

CompanyAdTenderSummary (string cui) 
- returns  numele companie, nr_achizitii si nr_licitatii
- /api/CompanyAdTenderSummary/:cui

**Comment by claudiughioc** [comment]
Reopening this one. All we need are one field in each of the following API calls:
- [ ] http://hbp-api.azurewebsites.net/api/TenderCompany/39213 will have an aditional field with the number of tenders

- [ ] http://hbp-api.azurewebsites.net/api/ADCompany/1556389 will have an aditional field with the number of ADs
